title: Laura Puzzello's Webpage
author:
  name: Laura Puzzello
  email: laura.puzzello@monash.edu

google_analytics: G-JB6FVVXKBH

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [ import ]

minima:
  skin: auto

  nav_pages:
    - index.md
    - research.md
    - cv.md
    - media-resources.md

  hide_site_feed_link: true
  social_links:
    - title: Laura Puzzello's GitHub
      icon: github
      url: "https://github.com/L-Puzzello"
    - title: Laura Puzzello's Twitter
      icon: x-twitter
      url: "https://x.com/Lpuzzell"
    - title: Laura Puzzello's LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/puzzello-laura-b81732b"
    - title: Laura Puzzello's Bluesky
      icon: bluesky
      url: "https://bsky.app/profile/lpuzzell.bsky.social"